version: "3.9"

services:
  db:
    image: postgres:16
    container_name: urbantrends-dev-db
    environment:
      POSTGRES_USER: urbantrends
      POSTGRES_PASSWORD: urban2026
      POSTGRES_DB: urbantrends_dev_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
    networks:
      - urbantrends-dev

  urbantrends-dev-backend:
    build: .  # <-- must have a value
    container_name: urbantrends-backend
    command: gunicorn urbantrends_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - urbantrends.env
    depends_on:
      - db
    networks:
      - urbantrends-dev

volumes:
  postgres_data:

networks:
  urbantrends-dev:
