# Generated by Django 6.0 on 2026-02-11 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbantrends_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('software-development', 'Software Development'), ('web-digital-solutions', 'Web & Digital Solutions'), ('cloud-infrastructure', 'Cloud Infrastructure'), ('ui/ux-product-design', 'UI/UX Product Design'), ('maintenance-support', 'Maintenance & Support'), ('consulting-strategy', 'Consulting & Strategy')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.AddField(
            model_name='servicetier',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicetier',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='urbantrends_services.order')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urbantrends_services.servicetier')),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urbantrends_services.serviceitem')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='servicetier',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='servicetier',
            name='service_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='urbantrends_services.serviceitem'),
        ),
        migrations.AlterUniqueTogether(
            name='servicetier',
            unique_together={('service_item', 'tier')},
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='services_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='urbantrends_services.services'),
        ),
        migrations.DeleteModel(
            name='ServiceCategories',
        ),
        migrations.RemoveField(
            model_name='servicetier',
            name='features',
        ),
        migrations.RemoveField(
            model_name='servicetier',
            name='service',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
