# Generated by Django 6.0 on 2026-02-20 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbantrends_services', '0002_serviceitem_services_remove_service_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicetier',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='servicetier',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicetier',
            name='service_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='urbantrends_services.serviceitem'),
        ),
        migrations.AddConstraint(
            model_name='servicetier',
            constraint=models.UniqueConstraint(fields=('service_item', 'tier'), name='unique_service_tier_per_item'),
        ),
    ]
