# Generated by Django 6.0 on 2026-04-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_projects', '0002_clientproject_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientproject',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='clientproject',
            name='phone',
        ),
        migrations.AddField(
            model_name='clientproject',
            name='completeness_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='detected_stack',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='error_flags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='integrity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='repo_access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='repo_branch',
            field=models.CharField(blank=True, default='main', max_length=100),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='repo_provider',
            field=models.CharField(blank=True, choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='repo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='scaffold_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='scaffold_graph',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='scaffold_output',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='scaffold_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('queued', 'Queued'), ('cloning', 'Cloning'), ('analyzing', 'Analyzing'), ('scaffolded', 'Scaffolded'), ('failed', 'Failed')], db_index=True, default='idle', max_length=20),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='scaffolded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientproject',
            name='suggestions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
