# Generated by Django 6.0 on 2026-01-22 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbantrends_projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devproject',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddConstraint(
            model_name='devproject',
            constraint=models.UniqueConstraint(fields=('title', 'created_by'), name='unique_project_per_user'),
        ),
    ]
