# Generated by Django 6.0 on 2026-03-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbantrends_brands', '0002_alter_createbrandsfoundation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbrandsfoundation',
            name='image',
            field=models.ImageField(default=' ', upload_to='brand_images/'),
            preserve_default=False,
        ),
    ]
