# Generated by Django 6.0 on 2026-03-23 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbantrends_brands', '0003_alter_createbrandsfoundation_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('NGN', 'Nigerian Naira'), ('ZAR', 'South African Rand'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('JPY', 'Japanese Yen'), ('INR', 'Indian Rupee'), ('BRL', 'Brazilian Real'), ('AED', 'UAE Dirham'), ('SGD', 'Singapore Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan')], default='USD', max_length=3)),
                ('region', models.CharField(choices=[('africa', 'Africa'), ('north_america', 'North America'), ('south_america', 'South America'), ('europe', 'Europe'), ('asia', 'Asia'), ('middle_east', 'Middle East'), ('oceania', 'Oceania'), ('global', 'Global')], default='global', max_length=20)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of features included in this tier')),
                ('max_modules', models.PositiveIntegerField(default=0, help_text='Max modules allowed. 0 = unlimited')),
                ('support_level', models.CharField(choices=[('email', 'Email Support'), ('priority', 'Priority Support'), ('dedicated', 'Dedicated Account Manager')], default='email', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='urbantrends_brands.createbrandsfoundation')),
            ],
            options={
                'ordering': ['brand', 'price'],
                'constraints': [models.UniqueConstraint(fields=('brand', 'tier', 'region'), name='unique_brand_tier_per_region')],
            },
        ),
    ]
