# Generated by Django 6.0 on 2026-03-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbantrends_brands', '0004_brandtier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbrandsfoundation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brand_images/'),
        ),
    ]
