# Generated by Django 6.0 on 2026-03-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbantrends_brands', '0005_alter_createbrandsfoundation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createbrandsfoundation',
            name='image',
            field=models.ImageField(default=' ', upload_to='brand_images/'),
            preserve_default=False,
        ),
    ]
