# Generated by Django 6.0 on 2026-01-28 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('project_category', models.CharField(max_length=255)),
                ('project_status', models.CharField(choices=[('local', 'Local'), ('published', 'Published')], default='local', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dashboard_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
